# Generated by Django 4.2 on 2023-09-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0002_alter_libro_titolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descrizione',
            field=models.CharField(default='', max_length=100),
        ),
    ]
